### ISSUE TITLE
about the rendered novel views

### ISSUE THREAD

**Issue by szhang963** [donydchen/mvsplat360#9]
Hi, thanks for your excellent work. I have some questions about the rendered novel view images by the command in README.md.
1. The rendered images (ImagesRefined0) are some inconsistencies in continuous frames, just like this,
![5c8dafad7d782c76ffad8c14e9e1244ce2b83aa12324c54a3cc10176964acf04_000048](https://github.com/user-attachments/assets/132cf02a-c035-4b21-9834-10cd04da645d)
![5c8dafad7d782c76ffad8c14e9e1244ce2b83aa12324c54a3cc10176964acf04_000054](https://github.com/user-attachments/assets/e0fcf8d2-f01d-44c5-8583-b039c33d034d)
and,
![8fdc5130f0731360cc053f59049bfe6db509567457c5471c970292966cb34f17_000117](https://github.com/user-attachments/assets/aceb1c12-e985-4f3b-a090-ced3c364116c)
![8fdc5130f0731360cc053f59049bfe6db509567457c5471c970292966cb34f17_000141](https://github.com/user-attachments/assets/01a6a738-acb7-4506-8671-24894acc6b07)

2. The rendered images (ImagesGSplat) have some artifacts.
![gs-5c8dafad7d782c76ffad8c14e9e1244ce2b83aa12324c54a3cc10176964acf04_000054](https://github.com/user-attachments/assets/210dfba0-dd45-4946-96a8-e02071662bd5)

Could you tell me some reasons above abnormal results?

Thanks.
Best.

**Comment by donydchen** [comment]
Hi, @szhang963, thanks for your interest in our work.

The 'ImagesRefined0' results are refined by the SVD, which can lead to some unexpected generated contents due to "hallucination", especially in regions unobserved in the inputs. You can check out the limitation section in [Appendix C. of the paper](https://arxiv.org/pdf/2411.04924#page=15.81) for more details. One of the potential solutions for this issue is to replace SVD with a more advanced video diffusion model, e.g., [CogVideoX](https://github.com/THUDM/CogVideo) or [HunyuanVideo](https://github.com/Tencent/HunyuanVideo). Still, there is no guarantee of thoroughly addressing this issue since maintaining 3D consistency in unobserved generated regions is ill-posed and challenging.

The 'ImagesGSplat' results are of low quality, as expected, which is why we used the following SVD module to refine these outputs further. You can take a look at the motivation presented in the Introduction of our paper for more details.

Hope it helps. Cheers.
